apiVersion: v1
kind: ConfigMap
metadata:
  name: roxsecret-namespaces
  namespace: stackrox
data:
  NAMESPACES: coolstore-cicd
  CENTRAL_URL: central-stackrox.apps.rosa-7mqx6.svnp.p1.openshiftapps.com